package ui;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class Properties {
    JPanel jPanel = new JPanel();
    String errorMessage = null;

    JPanel jPanel1 = new JPanel();
    JPanel jPanel2 = new JPanel();
    JPanel jPanel3 = new JPanel();
    JPanel jPanel4 = new JPanel();// 是否随机分配的单选按钮

    JLabel title = new JLabel("配置表格");

    JLabel jLabel1 = new JLabel("类别ID长度:");
    JLabel jLabel2 = new JLabel("缺失率:");
    JLabel jLabel3 = new JLabel("标签数目:");
    JLabel jLabel4 = new JLabel("标签类别：");
    JLabel jLabel5 = new JLabel("时隙数:");
    JLabel jLabel6 = new JLabel("平均每个类别的标签数量:");

    JLabel error = new JLabel(" ");
    JTextField jTextField1 = new JTextField();
    JTextField jTextField2 = new JTextField();
    JTextField jTextField3 = new JTextField();
    JTextField jTextField5 = new JTextField();
    JTextField jTextField6 = new JTextField();
    ButtonGroup bg = new ButtonGroup();
    JRadioButton jRadioButton1 = new JRadioButton("随机分配cid", true);
    JRadioButton jRadioButton2 = new JRadioButton("指定cid", false);

    JButton jButton1 = new JButton("确定");
    JButton jButton2 = new JButton("取消");


    public void assmbleProperties() {
        //标题
        jPanel1.add(title);

        //各个参数的标签和文字
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        jPanel2.add(jLabel1);
        jPanel2.add(jTextField1);

        jPanel2.add(jLabel2);
        jPanel2.add(jTextField2);

        jPanel2.add(jLabel3);
        jPanel2.add(jTextField3);

        jPanel4.add(jLabel4);

        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        jPanel4.add(jRadioButton1);
        jPanel4.add(jRadioButton2);
        jPanel2.add(jPanel4);

        jPanel2.add(jRadioButton1);
        jPanel.add(jRadioButton2);

        jPanel2.add(jLabel5);
        jPanel2.add(jTextField5);

        jPanel2.add(jLabel6);
        jPanel2.add(jTextField6);

        //确认/取消按钮
        jPanel3.add(jButton1);
        jPanel3.add(jButton2);

        //组装3个JPanel
        jPanel.setLayout(new BoxLayout(jPanel, BoxLayout.Y_AXIS));
        jPanel.add(jPanel1);
        jPanel.add(jPanel2);
        jPanel.add(jPanel3);

        jPanel.setPreferredSize(new Dimension(300, 150));
    }

    public static void main(String[] args) {
        Properties p = new Properties();
        p.assmbleProperties();
        JFrame f = new JFrame();
        f.add(p.jPanel);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        f.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //JOptionPane.showConfirmDialog(new JFrame(), p, "配置参数", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
